apiVersion: v1
kind: Service
metadata:
  name: rusi-sidecar-injector
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: https
    protocol: TCP
    name: https
  selector:
    app: rusi-sidecar-injector
