apiVersion: rusi.io/v1alpha1
kind: Component
metadata:
  name: natsstreaming-pubsub
spec:
  type: pubsub.natsstreaming
  version: v1
  metadata:
    - name: natsURL
      value: "nats://kube-worker1:31291"
    - name: natsStreamingClusterID
      value: faas-cluster
    - name: subscriptionType
      value: queue
    - name: connectWait
      value: 10s
    - name: ackWaitTime
      value: 50s
    - name: maxInFlight
      value: '1'
    - name: durableSubscriptionName
      value: durable
