apiVersion: rusi.io/v1alpha1
kind: Component
metadata:
  name: jetstream-pubsub
spec:
  type: pubsub.jetstream
  version: v1
  metadata:
    - name: natsURL
      value: "nats://kube-worker1:31552"
    - name: connectWait
      value: 10s
    - name: ackWaitTime
      value: 50s
    - name: maxInFlight
      value: '1'
