apiVersion: rusi.io/v1alpha1
kind: Configuration
metadata:
  name: node-pipeline-config
spec:
  metric:
    enabled: true
  tracing:
    samplingRate: '1'
    jaeger:
      useAgent: false
      collectorEndpointAddress: 'http://linux-ts1858:14268/api/traces'
#  subscriberPipeline:
#    handlers:
#    - name: pubsub-uppercase
#      type: middleware.pubsub.uppercase
  pubSub:
    name: jetstream-pubsub
