apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configurations.rusi.io
spec:
  group: rusi.io
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Configuration describes an Rusi configuration setting
          properties:
            apiVersion:
              description:
                "APIVersion defines the versioned schema of this representation
                of an object. Servers should convert recognized schemas to the latest
                internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
              type: string
            kind:
              description:
                "Kind is a string value representing the REST resource this
                object represents. Servers may infer this from the endpoint the client
                submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
              type: string
            metadata:
              type: object
            spec:
              description: ConfigurationSpec is the spec for an configuration
              properties:
                features:
                  items:
                    description: FeatureSpec defines the features that are enabled/disabled
                    properties:
                      enabled:
                        type: boolean
                      name:
                        type: string
                    required:
                      - enabled
                      - name
                    type: object
                  type: array
                subscriberPipeline:
                  description: PipelineSpec defines the middleware pipeline
                  properties:
                    handlers:
                      items:
                        description: HandlerSpec defines a request handlers
                        properties:
                          name:
                            type: string
                          type:
                            type: string
                        required:
                          - name
                          - type
                        type: object
                      type: array
                  required:
                    - handlers
                  type: object
                publisherPipeline:
                  description: PipelineSpec defines the middleware pipeline
                  properties:
                    handlers:
                      items:
                        description: HandlerSpec defines a request handlers
                        properties:
                          name:
                            type: string
                          type:
                            type: string
                        required:
                          - name
                          - type
                        type: object
                      type: array
                  required:
                    - handlers
                  type: object
                tracing:
                  description: TracingSpec is the spec object in ConfigurationSpec
                  properties:
                    jaeger:
                      type: object
                      description: Defines the Jaeger trace configurations
                      properties:
                        useAgent:
                          description: Determines if a Jaeger agent is used
                          type: boolean
                        collectorEndpointAddress:
                          description: The endpoint address of Jaeger collector to receive traces. Ignored if 'useAgent' is set.
                          type: string
                  required:
                    - jaeger
                  type: object
                pubSub:
                  description: Defines the default pubSub
                  properties:
                    name:
                      type: string
                  required:
                    - name
                  type: object
                minRuntimeVersion:
                  description: Defines the minimum required rusid version
                  type: string
              type: object
          type: object
      served: true
      storage: true
  names:
    kind: Configuration
    plural: configurations
    singular: configuration
    categories:
      - all
      - rusi
  scope: Namespaced
